version: 2.1

jobs:
  build:
    docker:
      - image: docker:24.0.7-cli  # Official Docker CLI with Compose V2

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.18  # Enables full Docker Engine access

      - run:
          name: Start services
          command: docker compose up -d

      - run:
          name: Wait for postgresdb to be healthy
          command: |
            echo "Waiting for 'postgresdb' to be healthy..."
            timeout=60
            while [ "$timeout" -gt 0 ]; do
              cid=$(docker compose ps -q postgresdb)
              status=$(docker inspect --format='{{.State.Health.Status}}' "$cid")
              echo "Health status: $status"
              if [ "$status" = "healthy" ]; then
                echo "Postgres is healthy!"
                break
              fi
              sleep 2
              timeout=$((timeout - 2))
            done

            if [ "$timeout" -le 0 ]; then
              echo "Postgres healthcheck timed out"
              docker compose logs
              exit 1
            fi

      - run:
          name: Run tests in /app
          command: docker compose exec app sh -c "cd /app && npm test"

      - run:
          name: Teardown
          when: always
          command: docker compose down

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
