version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Start Docker Compose
          command: |
            docker-compose -f docker-compose.yml up -d
      - run:
          name: Run Tests
          command: |
            # Wait for the database to be ready
            docker-compose exec postgresdb bash -c 'until pg_isready -U $DB_USER -d $DB_NAME; do sleep 1; done'
            # Run your integration tests here
            docker-compose exec app bash -c 'pytest tests/integration'
      - run:
          name: Stop Docker Compose
          command: |
            docker-compose down
